# Generated by Django 2.2.7 on 2019-11-26 21:25

from django.db import migrations, models
import pitter.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('pitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.CharField(default=pitter.models.base.default_uuid_id, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=30)),
                ('follower_id', models.CharField(max_length=30)),
                ('subscription_flag', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pitt',
            fields=[
                ('id', models.CharField(default=pitter.models.base.default_uuid_id, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=256)),
                ('audio_path', models.CharField(max_length=3000)),
                ('audio_decoded', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=pitter.models.base.default_uuid_id, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('profile_name', models.CharField(max_length=32)),
                ('email_address', models.CharField(max_length=128)),
                ('email_notifications_mode', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
