# Generated by Django 2.2.7 on 2019-11-20 21:45

from django.db import migrations, models
import pitter.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('pitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.CharField(default=pitter.models.base.default_uuid_id, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('follower_id', models.IntegerField()),
                ('subscription_date', models.DateTimeField()),
                ('subscription_flag', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
